#!/bin/sh
# configure-system.sh — Apply hostname, admin password, network, and service settings
# Query string params:
#   disk=<name>       (e.g. sda)
#   hostname=<name>   (e.g. dayshield)
#   password=<pass>   (plain-text; hashed with openssl or chpasswd)
#   iface=<name>      (e.g. eth0)
# Output: JSON  { "ok": true } | { "error": "message" }
#
# Assumes /mnt/target is mounted (install-rootfs + install-bootloader done).
# Must be POSIX-compliant and run as root.

set -eu

printf 'Content-Type: application/json\r\n'
printf '\r\n'

# ── Parse CGI query string ────────────────────────────────────────
parse_param() {
  # Usage: parse_param QUERY_STRING key
  printf '%s' "$1" | tr '&' '\n' | grep "^${2}=" | head -n1 | sed "s/^${2}=//" | \
    sed 's/+/ /g' | sed 's/%\([0-9A-Fa-f][0-9A-Fa-f]\)/\\x\1/g' | xargs printf '%b'
}

QS="${QUERY_STRING:-}"
DISK=$(parse_param "$QS" "disk")
HOSTNAME=$(parse_param "$QS" "hostname")
PASSWORD=$(parse_param "$QS" "password")
IFACE=$(parse_param "$QS" "iface")

# ── Validate ──────────────────────────────────────────────────────
if [ -z "$DISK" ]; then
  printf '{"error":"Missing required parameter: disk"}\n'; exit 1
fi
if [ -z "$HOSTNAME" ]; then
  printf '{"error":"Missing required parameter: hostname"}\n'; exit 1
fi
if [ -z "$PASSWORD" ]; then
  printf '{"error":"Missing required parameter: password"}\n'; exit 1
fi
if [ -z "$IFACE" ]; then
  printf '{"error":"Missing required parameter: iface"}\n'; exit 1
fi

# Validate hostname (RFC 952 / RFC 1123)
if ! printf '%s' "$HOSTNAME" | grep -qE '^[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?$'; then
  printf '{"error":"Invalid hostname: must be alphanumeric and hyphens only, max 63 chars"}\n'; exit 1
fi

TARGET="/mnt/target"

if [ ! -d "${TARGET}/etc" ]; then
  printf '{"error":"Target root not found at %s"}\n' "$TARGET"; exit 1
fi

# ── Set hostname ──────────────────────────────────────────────────
printf '%s\n' "$HOSTNAME" > "${TARGET}/etc/hostname"

# /etc/hosts
cat > "${TARGET}/etc/hosts" << EOF
127.0.0.1   localhost
127.0.1.1   ${HOSTNAME}
::1         localhost ip6-localhost ip6-loopback
EOF

# ── Set admin (root) password ─────────────────────────────────────
# Prefer openssl for deterministic hashed password generation
if command -v openssl >/dev/null 2>&1; then
  HASH=$(openssl passwd -6 -- "$PASSWORD" 2>/dev/null)
elif command -v python3 >/dev/null 2>&1; then
  HASH=$(python3 -c "import crypt,sys; print(crypt.crypt(sys.argv[1], crypt.mksalt(crypt.METHOD_SHA512)))" "$PASSWORD" 2>/dev/null)
else
  printf '{"error":"Cannot hash password: neither openssl nor python3 found"}\n'; exit 1
fi

if [ -z "$HASH" ]; then
  printf '{"error":"Password hashing failed"}\n'; exit 1
fi

# Update /etc/shadow — replace root entry
if [ -f "${TARGET}/etc/shadow" ]; then
  SHADOW_ESCAPED=$(printf '%s' "$HASH" | sed 's|[&/\\]|\\&|g')
  sed -i "s|^root:[^:]*:|root:${SHADOW_ESCAPED}:|" "${TARGET}/etc/shadow"
else
  printf '{"error":"/etc/shadow not found in target"}\n'; exit 1
fi

# ── Configure LAN interface ───────────────────────────────────────
NETDIR="${TARGET}/etc/dayshield"
mkdir -p "$NETDIR"

# Write DayShield network config
cat > "${NETDIR}/network.conf" << EOF
# DayShield network configuration
# Generated by installer on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
LAN_IFACE=${IFACE}
EOF

# Also write a systemd-networkd .network file if applicable
NETWORKD_DIR="${TARGET}/etc/systemd/network"
mkdir -p "$NETWORKD_DIR"
cat > "${NETWORKD_DIR}/10-lan.network" << EOF
[Match]
Name=${IFACE}

[Network]
DHCP=yes
EOF

# ── Enable dayshield-core service ─────────────────────────────────
SYSTEMD_MULTI_USER="${TARGET}/etc/systemd/system/multi-user.target.wants"
mkdir -p "$SYSTEMD_MULTI_USER"

SERVICE_SRC="${TARGET}/usr/lib/systemd/system/dayshield-core.service"
SERVICE_LINK="${SYSTEMD_MULTI_USER}/dayshield-core.service"

if [ -f "$SERVICE_SRC" ]; then
  ln -sf "/usr/lib/systemd/system/dayshield-core.service" "$SERVICE_LINK" 2>/dev/null || true
fi

# Also enable systemd-networkd
for svc in systemd-networkd systemd-resolved; do
  svc_path="${TARGET}/usr/lib/systemd/system/${svc}.service"
  if [ -f "$svc_path" ]; then
    ln -sf "/usr/lib/systemd/system/${svc}.service" \
       "${SYSTEMD_MULTI_USER}/${svc}.service" 2>/dev/null || true
  fi
done

# ── Write /etc/fstab ──────────────────────────────────────────────
DISK_NODE=$(printf '%s' "$DISK" | sed 's|^/dev/||')
EFI_PART="/dev/${DISK_NODE}1"
ROOT_PART="/dev/${DISK_NODE}2"
case "$DISK_NODE" in nvme*|mmcblk*) EFI_PART="/dev/${DISK_NODE}p1"; ROOT_PART="/dev/${DISK_NODE}p2" ;; esac

ROOT_UUID=$(blkid -s UUID -o value "$ROOT_PART" 2>/dev/null || true)
EFI_UUID=$(blkid -s UUID -o value "$EFI_PART" 2>/dev/null || true)

{
  printf '# /etc/fstab — generated by DayShield installer\n'
  if [ -n "$ROOT_UUID" ]; then
    printf 'UUID=%s  /          ext4  defaults,noatime  0 1\n' "$ROOT_UUID"
  else
    printf '%s  /          ext4  defaults,noatime  0 1\n' "$ROOT_PART"
  fi
  if [ -n "$EFI_UUID" ]; then
    printf 'UUID=%s  /boot/efi  vfat  umask=0077        0 2\n' "$EFI_UUID"
  else
    printf '%s  /boot/efi  vfat  umask=0077        0 2\n' "$EFI_PART"
  fi
  printf 'tmpfs       /tmp       tmpfs defaults,nosuid,nodev  0 0\n'
} > "${TARGET}/etc/fstab"

printf '{"ok":true}\n'
